In [1]:
# Import the libraries
import numpy as np
import pandas as pd

In [2]:
# version of Pandas
pd.__version__

'2.3.1'

In [3]:
# read the csv data into a data frame
df = pd.read_csv("https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv")

In [4]:
# display the data frame
df

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                     170            3.0       159.0     3413.433759   
1                     130            5.0        97.0     3149.664934   
2                     170            NaN        78.0     3079.038997   
3                     220            4.0         NaN     2542.392402   
4                     210            1.0       140.0     3460.870990   
...                   ...            ...         ...             ...   
9699                  140            5.0       164.0     2981.107371   
9700                  180            NaN       154.0     2439.525729   
9701                  220            2.0       138.0     2583.471318   
9702                  230            4.0       177.0     2905.527390   
9703                  270            3.0       140.0     2908.043477   

      acceleration  model_year  origin fuel_type         drivetrain  \
0             17.7        2003  Europe  Gasoline    All-wheel drive   
1             17.8        2007     USA  Gasoline  Front-wheel drive   
2             15.1        2018  Europe  Gasoline  Front-wheel drive   
3             20.2        2009     USA    Diesel    All-wheel drive   
4             14.4        2009  Europe  Gasoline    All-wheel drive   
...            ...         ...     ...       ...                ...   
9699          17.3        2013  Europe    Diesel  Front-wheel drive   
9700          15.0        2004     USA  Gasoline    All-wheel drive   
9701          15.1        2008     USA    Diesel    All-wheel drive   
9702          19.4        2011     USA    Diesel  Front-wheel drive   
9703          14.7        2005    Asia    Diesel    All-wheel drive   

      num_doors  fuel_efficiency_mpg  
0           0.0            13.231729  
1           0.0            13.688217  
2           0.0            14.246341  
3           2.0            16.912736  
4           2.0            12.488369  
...         ...                  ...  
9699        NaN            15.101802  
9700        0.0            17.962326  
9701       -1.0            17.186587  
9702        1.0            15.331551  
9703       -1.0            14.884467  

[9704 rows x 11 columns]

In [5]:
# count the nummber of unique fuel_types in the data frame
df['fuel_type'].nunique()

2

In [6]:
# To find how many columns in the data frame contain missing values, look at the non-zero values after isnull().sum()
df.isnull().sum()

engine_displacement      0
num_cylinders          482
horsepower             708
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

In [7]:
# To find the maximum fuel efficiency of cars from Asia
df.groupby(['origin'])['fuel_efficiency_mpg'].max()

origin
Asia      23.759123
Europe    25.967222
USA       24.971452
Name: fuel_efficiency_mpg, dtype: float64

In [8]:
# To find the median value of horsepower use the .median() function
df['horsepower'].median()

np.float64(149.0)

In [9]:
# To calculate the most frequent value of the same horsepower column use the .mode() function
df['horsepower'].mode()

0    152.0
Name: horsepower, dtype: float64

In [10]:
# To use fillna to fill in missing values in horsepower with the most frequent values from the previous step
new_df = df
new_df['horsepower'] = new_df['horsepower'].fillna(152.0)
new_df['horsepower'].median()

np.float64(152.0)

In [11]:
# Select all the cars from Asia
Asia_cars = df[df['origin'] == 'Asia']
Asia_cars_subset = Asia_cars[['vehicle_weight','model_year']]
Asia_cars_subset
Asia_cars_subset_7 = Asia_cars_subset.iloc[range(7)]
Asia_cars_subset_7

vehicle_weight  model_year
8      2714.219310        2016
12     2783.868974        2010
14     3582.687368        2007
20     2231.808142        2011
21     2659.431451        2016
34     2844.227534        2014
38     3761.994038        2019

In [12]:
# Get the underlying numpy array
X = Asia_cars_subset_7.values
X.shape

(7, 2)

In [13]:
# Compute matrix-matrix multiplication of transpose of X and X. To get the transpose of X, use X.T.
XT = X.T
XT.shape

(2, 7)

In [14]:
# Let us call the result of the matrix-matrix multiplication XTX
XTX = XT.dot(X)
XTX

array([[62248334.33150762, 41431216.5073268 ],
       [41431216.5073268 , 28373339.        ]])

In [15]:
# Invert XTX. We can use the np.linalg.inv()
XTX_inv = np.linalg.inv(XTX)
XTX_inv.shape
XTX_inv
XTX_inv.dot(XTX)

array([[ 1.00000000e+00,  2.13808046e-15],
       [-3.87615815e-15,  1.00000000e+00]])

In [16]:
# Create an array y with values as shown below
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
y.shape

(7,)

In [17]:
# Multiply the inverse if XTX with the transpose of X, and then multiply the result by y. Call the result w.
# I see two ways (1) (XTX_inv * XT) * y  (2) XTX_inv * (XT * y)
XTX_inv_XT = XTX_inv.dot(XT)
XTX_inv_XT.shape
XTX_inv_XT
w = XTX_inv_XT.dot(y)

#XT_y = XT.dot(y)
#XT_y.shape
#XT_y
#w = XTX_inv.dot(XT_y)
w

array([0.01386421, 0.5049067 ])

In [18]:
# To get the sum of the elements in the result
w.sum()

np.float64(0.5187709081074016)